# Site settings
title: Sagacia Soft
email: contact@sagaciasoft.com
baseurl:  /grayscale-theme
url: https://brittleigh.github.io
description: "Description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: 
  - title: facebook
    url:
  - title: linkedin
    url: 
  - title: instagram
    url: 
  - title: steam
    url: 
  - title: soundcloud
    url:

# Build settings
markdown: kramdown
permalink: pretty
